/********************************************************************
* TTrifoilPhysicsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTrifoilPhysicsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTrifoilPhysicsDict();
extern void G__cpp_setup_inheritanceTTrifoilPhysicsDict();
extern void G__cpp_setup_typetableTTrifoilPhysicsDict();
extern void G__cpp_setup_memvarTTrifoilPhysicsDict();
extern void G__cpp_setup_globalTTrifoilPhysicsDict();
extern void G__cpp_setup_memfuncTTrifoilPhysicsDict();
extern void G__cpp_setup_funcTTrifoilPhysicsDict();
extern void G__set_cpp_environmentTTrifoilPhysicsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTrifoilPhysics.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TClass;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TBuffer;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMemberInspector;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TObject;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_string;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlETH1FcOallocatorlETH1FgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_reverse_iteratorlEvectorlETH1FcOallocatorlETH1FgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TTrifoilData;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_NPA;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_NPAcLcLVDetector;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TTrifoilPhysicsDictLN_TTrifoilPhysics;

/* STUB derived class for protected member access */
