/********************************************************************
* TEurogamDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TEurogamDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTEurogamDataDict();
extern void G__cpp_setup_inheritanceTEurogamDataDict();
extern void G__cpp_setup_typetableTEurogamDataDict();
extern void G__cpp_setup_memvarTEurogamDataDict();
extern void G__cpp_setup_globalTEurogamDataDict();
extern void G__cpp_setup_memfuncTEurogamDataDict();
extern void G__cpp_setup_funcTEurogamDataDict();
extern void G__set_cpp_environmentTEurogamDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TEurogamData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TEurogamDataDictLN_TClass;
extern G__linked_taginfo G__TEurogamDataDictLN_TBuffer;
extern G__linked_taginfo G__TEurogamDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TEurogamDataDictLN_TObject;
extern G__linked_taginfo G__TEurogamDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TEurogamDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TEurogamDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TEurogamDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEurogamDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TEurogamDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEurogamDataDictLN_TEurogamData;

/* STUB derived class for protected member access */
