# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.

# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "New viewer" "{gui_vis}"
/gui/addButton viewer "Set style surface" "{gui_surface}"
/gui/addButton viewer "Set style wireframe" "{gui_wireframe}"

# Custom visualisation menu
/gui/addMenu custom "Custom View"
/gui/addButton custom "Add axis" "/vis/scene/add/axes"
/gui/addButton custom "Add beam axis" "{gui_beam}"
/gui/addButton custom "Add event ID" "/vis/scene/add/eventID"
/gui/addButton custom "Add step point" "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true"

# No hit collection is implemented
#/gui/addButton custom "Add Scorer Hits" "/vis/scene/add/psHits"
#/gui/addButton custom "Add Hits" "/vis/scene/add/hits"

# NPS tool bar
/gui/addIcon "Follow us on GitHub" user_icon "/gui/system {gui_nptool}" /Users/am0067/Desktop/nptool/NPSimulation/icons/NPToolLogo.png
/gui/addIcon "Exit" user_icon "{gui_exit}" /Users/am0067/Desktop/nptool/NPSimulation/icons/power.png
/gui/addIcon "the star gaze" user_icon "{gui_empty}" /Users/am0067/Desktop/nptool/NPSimulation/icons/empty.png 
/gui/addIcon "Update geometry" user_icon "{gui_update}" /Users/am0067/Desktop/nptool/NPSimulation/icons/recycle.png
/gui/addIcon "Update generator" user_icon "/gen/update" /Users/am0067/Desktop/nptool/NPSimulation/icons/bolt.png
/gui/addIcon "Open generator" user_icon "/gen/open" /Users/am0067/Desktop/nptool/NPSimulation/icons/folder.png
/gui/addIcon "the moon beyond the clouds" user_icon "{gui_empty}" /Users/am0067/Desktop/nptool/NPSimulation/icons/empty.png 
/gui/addIcon "Run beam on" user_icon "/run/beamOn" /Users/am0067/Desktop/nptool/NPSimulation/icons/rocket.png
/gui/addIcon "One event" user_icon "{gui_beamon}" /Users/am0067/Desktop/nptool/NPSimulation/icons/play.png
/gui/addIcon "Activate tracking verbose" user_icon "{gui_tracking}" /Users/am0067/Desktop/nptool/NPSimulation/icons/shoeprints.png
/gui/addIcon "fill the empty dark" user_icon "{gui_empty}" /Users/am0067/Desktop/nptool/NPSimulation/icons/empty.png 
/gui/addIcon "View Browser" user_icon "{gui_browser}" /Users/am0067/Desktop/nptool/NPSimulation/icons/browser.png
/gui/addIcon "Take a screen shot" user_icon "/vis/ogl/printEPS" /Users/am0067/Desktop/nptool/NPSimulation/icons/camera.png
/gui/addIcon "Home" user_icon     "{gui_home}" /Users/am0067/Desktop/nptool/NPSimulation/icons/eye.png
/gui/addIcon "Front" user_icon    "{gui_front}" /Users/am0067/Desktop/nptool/NPSimulation/icons/arrow-up.png
/gui/addIcon "Back" user_icon     "{gui_back}" /Users/am0067/Desktop/nptool/NPSimulation/icons/arrow-down.png
/gui/addIcon "Left" user_icon     "{gui_left}" /Users/am0067/Desktop/nptool/NPSimulation/icons/arrow-left.png
/gui/addIcon "Right" user_icon    "{gui_right}" /Users/am0067/Desktop/nptool/NPSimulation/icons/arrow-right.png
/gui/addIcon "Zoom in" user_icon  "{gui_zoomin}" /Users/am0067/Desktop/nptool/NPSimulation/icons/zoomin.png
/gui/addIcon "Zoom out" user_icon "{gui_zoomout}" /Users/am0067/Desktop/nptool/NPSimulation/icons/zoomout.png

