/********************************************************************
* TDUMMYDetectorDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TDUMMYDetectorDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTDUMMYDetectorDataDict();
extern void G__cpp_setup_inheritanceTDUMMYDetectorDataDict();
extern void G__cpp_setup_typetableTDUMMYDetectorDataDict();
extern void G__cpp_setup_memvarTDUMMYDetectorDataDict();
extern void G__cpp_setup_globalTDUMMYDetectorDataDict();
extern void G__cpp_setup_memfuncTDUMMYDetectorDataDict();
extern void G__cpp_setup_funcTDUMMYDetectorDataDict();
extern void G__set_cpp_environmentTDUMMYDetectorDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDUMMYDetectorData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_TClass;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_TBuffer;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_TObject;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDUMMYDetectorDataDictLN_TDUMMYDetectorData;

/* STUB derived class for protected member access */
