//
// File generated by rootcint at Tue Jul 17 16:41:38 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TVamosCHIODataDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TVamosCHIODataDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TVamosCHIOData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TVamosCHIOData(void *p = 0);
   static void *newArray_TVamosCHIOData(Long_t size, void *p);
   static void delete_TVamosCHIOData(void *p);
   static void deleteArray_TVamosCHIOData(void *p);
   static void destruct_TVamosCHIOData(void *p);
   static void streamer_TVamosCHIOData(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TVamosCHIOData*)
   {
      ::TVamosCHIOData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVamosCHIOData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TVamosCHIOData", ::TVamosCHIOData::Class_Version(), "./TVamosCHIOData.h", 31,
                  typeid(::TVamosCHIOData), DefineBehavior(ptr, ptr),
                  &::TVamosCHIOData::Dictionary, isa_proxy, 0,
                  sizeof(::TVamosCHIOData) );
      instance.SetNew(&new_TVamosCHIOData);
      instance.SetNewArray(&newArray_TVamosCHIOData);
      instance.SetDelete(&delete_TVamosCHIOData);
      instance.SetDeleteArray(&deleteArray_TVamosCHIOData);
      instance.SetDestructor(&destruct_TVamosCHIOData);
      instance.SetStreamerFunc(&streamer_TVamosCHIOData);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TVamosCHIOData*)
   {
      return GenerateInitInstanceLocal((::TVamosCHIOData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TVamosCHIOData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TVamosCHIOData::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TVamosCHIOData::Class_Name()
{
   return "TVamosCHIOData";
}

//______________________________________________________________________________
const char *TVamosCHIOData::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVamosCHIOData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TVamosCHIOData::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVamosCHIOData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TVamosCHIOData::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVamosCHIOData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TVamosCHIOData::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVamosCHIOData*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TVamosCHIOData::Streamer(TBuffer &R__b)
{
   // Stream an object of class TVamosCHIOData.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_A_PadNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_A_Energy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_B_PadNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_B_Energy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_C_PadNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_C_Energy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, TVamosCHIOData::IsA());
   } else {
      R__c = R__b.WriteVersion(TVamosCHIOData::IsA(), kTRUE);
      TObject::Streamer(R__b);
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_A_PadNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_A_Energy;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_B_PadNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_B_Energy;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_C_PadNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fVamos_CHIO_C_Energy;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TVamosCHIOData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TVamosCHIOData.
      TClass *R__cl = ::TVamosCHIOData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVamos_CHIO_A_PadNbr", (void*)&fVamos_CHIO_A_PadNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fVamos_CHIO_A_PadNbr, "fVamos_CHIO_A_PadNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVamos_CHIO_A_Energy", (void*)&fVamos_CHIO_A_Energy);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fVamos_CHIO_A_Energy, "fVamos_CHIO_A_Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVamos_CHIO_B_PadNbr", (void*)&fVamos_CHIO_B_PadNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fVamos_CHIO_B_PadNbr, "fVamos_CHIO_B_PadNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVamos_CHIO_B_Energy", (void*)&fVamos_CHIO_B_Energy);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fVamos_CHIO_B_Energy, "fVamos_CHIO_B_Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVamos_CHIO_C_PadNbr", (void*)&fVamos_CHIO_C_PadNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fVamos_CHIO_C_PadNbr, "fVamos_CHIO_C_PadNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVamos_CHIO_C_Energy", (void*)&fVamos_CHIO_C_Energy);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fVamos_CHIO_C_Energy, "fVamos_CHIO_C_Energy.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TVamosCHIOData(void *p) {
      return  p ? new(p) ::TVamosCHIOData : new ::TVamosCHIOData;
   }
   static void *newArray_TVamosCHIOData(Long_t nElements, void *p) {
      return p ? new(p) ::TVamosCHIOData[nElements] : new ::TVamosCHIOData[nElements];
   }
   // Wrapper around operator delete
   static void delete_TVamosCHIOData(void *p) {
      delete ((::TVamosCHIOData*)p);
   }
   static void deleteArray_TVamosCHIOData(void *p) {
      delete [] ((::TVamosCHIOData*)p);
   }
   static void destruct_TVamosCHIOData(void *p) {
      typedef ::TVamosCHIOData current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TVamosCHIOData(TBuffer &buf, void *obj) {
      ((::TVamosCHIOData*)obj)->::TVamosCHIOData::Streamer(buf);
   }
} // end of namespace ROOT for class ::TVamosCHIOData

namespace ROOT {
   void vectorlEunsignedsPshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPshortgR_Dictionary();
   static void *new_vectorlEunsignedsPshortgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPshortgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPshortgR(void *p);
   static void deleteArray_vectorlEunsignedsPshortgR(void *p);
   static void destruct_vectorlEunsignedsPshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned short>*)
   {
      vector<unsigned short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned short>", -2, "vector.dll", 0,
                  typeid(vector<unsigned short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned short>) );
      instance.SetNew(&new_vectorlEunsignedsPshortgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPshortgR);
      instance.SetDelete(&delete_vectorlEunsignedsPshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPshortgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<unsigned short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<unsigned short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short> : new vector<unsigned short>;
   }
   static void *newArray_vectorlEunsignedsPshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short>[nElements] : new vector<unsigned short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPshortgR(void *p) {
      delete ((vector<unsigned short>*)p);
   }
   static void deleteArray_vectorlEunsignedsPshortgR(void *p) {
      delete [] ((vector<unsigned short>*)p);
   }
   static void destruct_vectorlEunsignedsPshortgR(void *p) {
      typedef vector<unsigned short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<unsigned short>

/********************************************************
* TVamosCHIODataDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTVamosCHIODataDict();

extern "C" void G__set_cpp_environmentTVamosCHIODataDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TVamosCHIOData.h");
  G__cpp_reset_tagtableTVamosCHIODataDict();
}
#include <new>
extern "C" int G__cpp_dllrevTVamosCHIODataDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TVamosCHIOData */
static int G__TVamosCHIODataDict_162_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVamosCHIOData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TVamosCHIOData[n];
     } else {
       p = new((void*) gvp) TVamosCHIOData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TVamosCHIOData;
     } else {
       p = new((void*) gvp) TVamosCHIOData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->SetVamosCHIOPadNbrA((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->SetVamosCHIOEnergyA((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->SetVamosCHIOPadNbrB((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->SetVamosCHIOEnergyB((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->SetVamosCHIOPadNbrC((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->SetVamosCHIOEnergyC((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOMultA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOPadNbrA((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOEnergyA((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOMultB());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOPadNbrB((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOEnergyB((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOMultC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOPadNbrC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((TVamosCHIOData*) G__getstructoffset())->GetVamosCHIOEnergyC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TVamosCHIOData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVamosCHIOData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TVamosCHIOData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TVamosCHIOData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVamosCHIOData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVamosCHIOData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVamosCHIOData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVamosCHIOData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TVamosCHIODataDict_162_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVamosCHIOData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TVamosCHIODataDict_162_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TVamosCHIOData* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TVamosCHIOData(*(TVamosCHIOData*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TVamosCHIOData G__TTVamosCHIOData;
static int G__TVamosCHIODataDict_162_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TVamosCHIOData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TVamosCHIOData*) (soff+(sizeof(TVamosCHIOData)*i)))->~G__TTVamosCHIOData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TVamosCHIOData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TVamosCHIOData*) (soff))->~G__TTVamosCHIOData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TVamosCHIODataDict_162_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVamosCHIOData* dest = (TVamosCHIOData*) G__getstructoffset();
   *dest = *(TVamosCHIOData*) libp->para[0].ref;
   const TVamosCHIOData& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TVamosCHIOData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTVamosCHIODataDict {
 public:
  G__Sizep2memfuncTVamosCHIODataDict(): p(&G__Sizep2memfuncTVamosCHIODataDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTVamosCHIODataDict::*p)();
};

size_t G__get_sizep2memfuncTVamosCHIODataDict()
{
  G__Sizep2memfuncTVamosCHIODataDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTVamosCHIODataDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData))) {
     TVamosCHIOData *G__Lderived;
     G__Lderived=(TVamosCHIOData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData),G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTVamosCHIODataDict() {

   /* Setting up typedef entry */
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TVamosCHIOData */
static void G__setup_memvarTVamosCHIOData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData));
   { TVamosCHIOData *p; p=(TVamosCHIOData*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fVamos_CHIO_A_PadNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fVamos_CHIO_A_Energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fVamos_CHIO_B_PadNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fVamos_CHIO_B_Energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fVamos_CHIO_C_PadNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fVamos_CHIO_C_Energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTVamosCHIODataDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTVamosCHIOData(void) {
   /* TVamosCHIOData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData));
   G__memfunc_setup("TVamosCHIOData",1271,G__TVamosCHIODataDict_162_0_1, 105, G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__TVamosCHIODataDict_162_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Dump",406,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetVamosCHIOPadNbrA",1741,G__TVamosCHIODataDict_162_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - PadNbrA", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVamosCHIOEnergyA",1792,G__TVamosCHIODataDict_162_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - EnergyA", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVamosCHIOPadNbrB",1742,G__TVamosCHIODataDict_162_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - PadNbrB", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVamosCHIOEnergyB",1793,G__TVamosCHIODataDict_162_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - EnergyB", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVamosCHIOPadNbrC",1743,G__TVamosCHIODataDict_162_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - PadNbrC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVamosCHIOEnergyC",1794,G__TVamosCHIODataDict_162_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - EnergyC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOMultA",1580,G__TVamosCHIODataDict_162_0_11, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOPadNbrA",1729,G__TVamosCHIODataDict_162_0_12, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOEnergyA",1780,G__TVamosCHIODataDict_162_0_13, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOMultB",1581,G__TVamosCHIODataDict_162_0_14, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOPadNbrB",1730,G__TVamosCHIODataDict_162_0_15, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOEnergyB",1781,G__TVamosCHIODataDict_162_0_16, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOMultC",1582,G__TVamosCHIODataDict_162_0_17, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOPadNbrC",1731,G__TVamosCHIODataDict_162_0_18, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVamosCHIOEnergyC",1782,G__TVamosCHIODataDict_162_0_19, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TVamosCHIODataDict_162_0_20, 85, G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TVamosCHIOData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TVamosCHIODataDict_162_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVamosCHIOData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TVamosCHIODataDict_162_0_22, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TVamosCHIOData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TVamosCHIODataDict_162_0_23, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TVamosCHIOData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TVamosCHIODataDict_162_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TVamosCHIODataDict_162_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVamosCHIOData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TVamosCHIODataDict_162_0_29, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVamosCHIOData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TVamosCHIODataDict_162_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVamosCHIOData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TVamosCHIODataDict_162_0_31, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVamosCHIOData::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TVamosCHIOData", 1271, G__TVamosCHIODataDict_162_0_32, (int) ('i'), G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData), -1, 0, 1, 1, 1, 0, "u 'TVamosCHIOData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TVamosCHIOData", 1397, G__TVamosCHIODataDict_162_0_33, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TVamosCHIODataDict_162_0_34, (int) ('u'), G__get_linked_tagnum(&G__TVamosCHIODataDictLN_TVamosCHIOData), -1, 1, 1, 1, 1, 0, "u 'TVamosCHIOData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTVamosCHIODataDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTVamosCHIODataDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTVamosCHIODataDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TVamosCHIODataDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TVamosCHIODataDictLN_TVamosCHIOData = { "TVamosCHIOData" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTVamosCHIODataDict() {
  G__TVamosCHIODataDictLN_TClass.tagnum = -1 ;
  G__TVamosCHIODataDictLN_TBuffer.tagnum = -1 ;
  G__TVamosCHIODataDictLN_TMemberInspector.tagnum = -1 ;
  G__TVamosCHIODataDictLN_TObject.tagnum = -1 ;
  G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__TVamosCHIODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TVamosCHIODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TVamosCHIODataDictLN_TVamosCHIOData.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTVamosCHIODataDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TVamosCHIODataDictLN_TVamosCHIOData),sizeof(TVamosCHIOData),-1,29952,"VamosCHIOData structure",G__setup_memvarTVamosCHIOData,G__setup_memfuncTVamosCHIOData);
}
extern "C" void G__cpp_setupTVamosCHIODataDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTVamosCHIODataDict()");
  G__set_cpp_environmentTVamosCHIODataDict();
  G__cpp_setup_tagtableTVamosCHIODataDict();

  G__cpp_setup_inheritanceTVamosCHIODataDict();

  G__cpp_setup_typetableTVamosCHIODataDict();

  G__cpp_setup_memvarTVamosCHIODataDict();

  G__cpp_setup_memfuncTVamosCHIODataDict();
  G__cpp_setup_globalTVamosCHIODataDict();
  G__cpp_setup_funcTVamosCHIODataDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTVamosCHIODataDict();
  return;
}
class G__cpp_setup_initTVamosCHIODataDict {
  public:
    G__cpp_setup_initTVamosCHIODataDict() { G__add_setup_func("TVamosCHIODataDict",(G__incsetup)(&G__cpp_setupTVamosCHIODataDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTVamosCHIODataDict() { G__remove_setup_func("TVamosCHIODataDict"); }
};
G__cpp_setup_initTVamosCHIODataDict G__cpp_setup_initializerTVamosCHIODataDict;

