//
// File generated by rootcint at Thu Nov  1 10:31:35 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TComptonTelescopeDataDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TComptonTelescopeDataDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TComptonTelescopeData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TComptonTelescopeData(void *p = 0);
   static void *newArray_TComptonTelescopeData(Long_t size, void *p);
   static void delete_TComptonTelescopeData(void *p);
   static void deleteArray_TComptonTelescopeData(void *p);
   static void destruct_TComptonTelescopeData(void *p);
   static void streamer_TComptonTelescopeData(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TComptonTelescopeData*)
   {
      ::TComptonTelescopeData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TComptonTelescopeData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TComptonTelescopeData", ::TComptonTelescopeData::Class_Version(), "./TComptonTelescopeData.h", 29,
                  typeid(::TComptonTelescopeData), DefineBehavior(ptr, ptr),
                  &::TComptonTelescopeData::Dictionary, isa_proxy, 0,
                  sizeof(::TComptonTelescopeData) );
      instance.SetNew(&new_TComptonTelescopeData);
      instance.SetNewArray(&newArray_TComptonTelescopeData);
      instance.SetDelete(&delete_TComptonTelescopeData);
      instance.SetDeleteArray(&deleteArray_TComptonTelescopeData);
      instance.SetDestructor(&destruct_TComptonTelescopeData);
      instance.SetStreamerFunc(&streamer_TComptonTelescopeData);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TComptonTelescopeData*)
   {
      return GenerateInitInstanceLocal((::TComptonTelescopeData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TComptonTelescopeData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TComptonTelescopeData::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TComptonTelescopeData::Class_Name()
{
   return "TComptonTelescopeData";
}

//______________________________________________________________________________
const char *TComptonTelescopeData::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TComptonTelescopeData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TComptonTelescopeData::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TComptonTelescopeData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TComptonTelescopeData::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TComptonTelescopeData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TComptonTelescopeData::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TComptonTelescopeData*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TComptonTelescopeData::Streamer(TBuffer &R__b)
{
   // Stream an object of class TComptonTelescopeData.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontE_TowerNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontE_DetectorNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontE_StripNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_FrontE_Energy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontT_TowerNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontT_DetectorNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontT_StripNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_FrontT_Time;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackE_TowerNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackE_DetectorNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackE_StripNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_BackE_Energy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackT_TowerNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackT_DetectorNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackT_StripNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_BackT_Time;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_E_TowerNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_E_DetectorNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_E_ChannelNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Calorimeter_E_Energy;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_T_TowerNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_T_DetectorNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_T_ChannelNbr;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            unsigned short R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Calorimeter_T_Time;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, TComptonTelescopeData::IsA());
   } else {
      R__c = R__b.WriteVersion(TComptonTelescopeData::IsA(), kTRUE);
      TObject::Streamer(R__b);
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontE_TowerNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontE_DetectorNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontE_StripNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_FrontE_Energy;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontT_TowerNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontT_DetectorNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_FrontT_StripNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_FrontT_Time;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackE_TowerNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackE_DetectorNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackE_StripNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_BackE_Energy;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackT_TowerNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackT_DetectorNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Tracker_BackT_StripNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Tracker_BackT_Time;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_E_TowerNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_E_DetectorNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_E_ChannelNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Calorimeter_E_Energy;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_T_TowerNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_T_DetectorNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<UShort_t> &R__stl =  fCT_Calorimeter_T_ChannelNbr;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<UShort_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fCT_Calorimeter_T_Time;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TComptonTelescopeData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TComptonTelescopeData.
      TClass *R__cl = ::TComptonTelescopeData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontE_TowerNbr", (void*)&fCT_Tracker_FrontE_TowerNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_FrontE_TowerNbr, "fCT_Tracker_FrontE_TowerNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontE_DetectorNbr", (void*)&fCT_Tracker_FrontE_DetectorNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_FrontE_DetectorNbr, "fCT_Tracker_FrontE_DetectorNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontE_StripNbr", (void*)&fCT_Tracker_FrontE_StripNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_FrontE_StripNbr, "fCT_Tracker_FrontE_StripNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontE_Energy", (void*)&fCT_Tracker_FrontE_Energy);
      R__insp.InspectMember("vector<Double_t>", (void*)&fCT_Tracker_FrontE_Energy, "fCT_Tracker_FrontE_Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontT_TowerNbr", (void*)&fCT_Tracker_FrontT_TowerNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_FrontT_TowerNbr, "fCT_Tracker_FrontT_TowerNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontT_DetectorNbr", (void*)&fCT_Tracker_FrontT_DetectorNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_FrontT_DetectorNbr, "fCT_Tracker_FrontT_DetectorNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontT_StripNbr", (void*)&fCT_Tracker_FrontT_StripNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_FrontT_StripNbr, "fCT_Tracker_FrontT_StripNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_FrontT_Time", (void*)&fCT_Tracker_FrontT_Time);
      R__insp.InspectMember("vector<Double_t>", (void*)&fCT_Tracker_FrontT_Time, "fCT_Tracker_FrontT_Time.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackE_TowerNbr", (void*)&fCT_Tracker_BackE_TowerNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_BackE_TowerNbr, "fCT_Tracker_BackE_TowerNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackE_DetectorNbr", (void*)&fCT_Tracker_BackE_DetectorNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_BackE_DetectorNbr, "fCT_Tracker_BackE_DetectorNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackE_StripNbr", (void*)&fCT_Tracker_BackE_StripNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_BackE_StripNbr, "fCT_Tracker_BackE_StripNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackE_Energy", (void*)&fCT_Tracker_BackE_Energy);
      R__insp.InspectMember("vector<Double_t>", (void*)&fCT_Tracker_BackE_Energy, "fCT_Tracker_BackE_Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackT_TowerNbr", (void*)&fCT_Tracker_BackT_TowerNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_BackT_TowerNbr, "fCT_Tracker_BackT_TowerNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackT_DetectorNbr", (void*)&fCT_Tracker_BackT_DetectorNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_BackT_DetectorNbr, "fCT_Tracker_BackT_DetectorNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackT_StripNbr", (void*)&fCT_Tracker_BackT_StripNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Tracker_BackT_StripNbr, "fCT_Tracker_BackT_StripNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Tracker_BackT_Time", (void*)&fCT_Tracker_BackT_Time);
      R__insp.InspectMember("vector<Double_t>", (void*)&fCT_Tracker_BackT_Time, "fCT_Tracker_BackT_Time.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_E_TowerNbr", (void*)&fCT_Calorimeter_E_TowerNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Calorimeter_E_TowerNbr, "fCT_Calorimeter_E_TowerNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_E_DetectorNbr", (void*)&fCT_Calorimeter_E_DetectorNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Calorimeter_E_DetectorNbr, "fCT_Calorimeter_E_DetectorNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_E_ChannelNbr", (void*)&fCT_Calorimeter_E_ChannelNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Calorimeter_E_ChannelNbr, "fCT_Calorimeter_E_ChannelNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_E_Energy", (void*)&fCT_Calorimeter_E_Energy);
      R__insp.InspectMember("vector<Double_t>", (void*)&fCT_Calorimeter_E_Energy, "fCT_Calorimeter_E_Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_T_TowerNbr", (void*)&fCT_Calorimeter_T_TowerNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Calorimeter_T_TowerNbr, "fCT_Calorimeter_T_TowerNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_T_DetectorNbr", (void*)&fCT_Calorimeter_T_DetectorNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Calorimeter_T_DetectorNbr, "fCT_Calorimeter_T_DetectorNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_T_ChannelNbr", (void*)&fCT_Calorimeter_T_ChannelNbr);
      R__insp.InspectMember("vector<UShort_t>", (void*)&fCT_Calorimeter_T_ChannelNbr, "fCT_Calorimeter_T_ChannelNbr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCT_Calorimeter_T_Time", (void*)&fCT_Calorimeter_T_Time);
      R__insp.InspectMember("vector<Double_t>", (void*)&fCT_Calorimeter_T_Time, "fCT_Calorimeter_T_Time.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TComptonTelescopeData(void *p) {
      return  p ? new(p) ::TComptonTelescopeData : new ::TComptonTelescopeData;
   }
   static void *newArray_TComptonTelescopeData(Long_t nElements, void *p) {
      return p ? new(p) ::TComptonTelescopeData[nElements] : new ::TComptonTelescopeData[nElements];
   }
   // Wrapper around operator delete
   static void delete_TComptonTelescopeData(void *p) {
      delete ((::TComptonTelescopeData*)p);
   }
   static void deleteArray_TComptonTelescopeData(void *p) {
      delete [] ((::TComptonTelescopeData*)p);
   }
   static void destruct_TComptonTelescopeData(void *p) {
      typedef ::TComptonTelescopeData current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TComptonTelescopeData(TBuffer &buf, void *obj) {
      ((::TComptonTelescopeData*)obj)->::TComptonTelescopeData::Streamer(buf);
   }
} // end of namespace ROOT for class ::TComptonTelescopeData

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEunsignedsPshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPshortgR_Dictionary();
   static void *new_vectorlEunsignedsPshortgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPshortgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPshortgR(void *p);
   static void deleteArray_vectorlEunsignedsPshortgR(void *p);
   static void destruct_vectorlEunsignedsPshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned short>*)
   {
      vector<unsigned short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned short>", -2, "vector.dll", 0,
                  typeid(vector<unsigned short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned short>) );
      instance.SetNew(&new_vectorlEunsignedsPshortgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPshortgR);
      instance.SetDelete(&delete_vectorlEunsignedsPshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPshortgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<unsigned short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<unsigned short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short> : new vector<unsigned short>;
   }
   static void *newArray_vectorlEunsignedsPshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short>[nElements] : new vector<unsigned short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPshortgR(void *p) {
      delete ((vector<unsigned short>*)p);
   }
   static void deleteArray_vectorlEunsignedsPshortgR(void *p) {
      delete [] ((vector<unsigned short>*)p);
   }
   static void destruct_vectorlEunsignedsPshortgR(void *p) {
      typedef vector<unsigned short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<unsigned short>

/********************************************************
* TComptonTelescopeDataDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTComptonTelescopeDataDict();

extern "C" void G__set_cpp_environmentTComptonTelescopeDataDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TComptonTelescopeData.h");
  G__cpp_reset_tagtableTComptonTelescopeDataDict();
}
#include <new>
extern "C" int G__cpp_dllrevTComptonTelescopeDataDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TComptonTelescopeData */
static int G__TComptonTelescopeDataDict_162_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TComptonTelescopeData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TComptonTelescopeData[n];
     } else {
       p = new((void*) gvp) TComptonTelescopeData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TComptonTelescopeData;
     } else {
       p = new((void*) gvp) TComptonTelescopeData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontETowerNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontEDetectorNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontEStripNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontEEnergy((const Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontTTowerNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontTDetectorNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontTStripNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerFrontTTime((const Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackETowerNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackEDetectorNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackEStripNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackEEnergy((const Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackTTowerNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackTDetectorNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackTStripNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTTrackerBackTTime((const Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterETowerNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterEDetectorNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterEChannelNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterEEnergy((const Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterTTowerNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterTDetectorNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterTChannelNbr((const UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->SetCTCalorimeterTTime((const Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontEMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontETowerNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontEDetectorNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontEStripNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontEEnergy((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontTMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontTTowerNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontTDetectorNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontTStripNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerFrontTTime((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackEMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackETowerNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackEDetectorNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackEStripNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackEEnergy((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackTMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTrackerTBackTTowerNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackTDetectorNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackTStripNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTTrackerBackTTime((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterEMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterETowerNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterEDetectorNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterEChannelNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterEEnergy((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterTMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterTTowerNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterTDetectorNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterTChannelNbr((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TComptonTelescopeData*) G__getstructoffset())->GetCTCalorimeterTTime((const Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TComptonTelescopeData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TComptonTelescopeData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TComptonTelescopeData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TComptonTelescopeData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TComptonTelescopeData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TComptonTelescopeData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TComptonTelescopeData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TComptonTelescopeData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TComptonTelescopeDataDict_162_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TComptonTelescopeData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TComptonTelescopeDataDict_162_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TComptonTelescopeData* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TComptonTelescopeData(*(TComptonTelescopeData*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TComptonTelescopeData G__TTComptonTelescopeData;
static int G__TComptonTelescopeDataDict_162_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TComptonTelescopeData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TComptonTelescopeData*) (soff+(sizeof(TComptonTelescopeData)*i)))->~G__TTComptonTelescopeData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TComptonTelescopeData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TComptonTelescopeData*) (soff))->~G__TTComptonTelescopeData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TComptonTelescopeDataDict_162_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TComptonTelescopeData* dest = (TComptonTelescopeData*) G__getstructoffset();
   *dest = *(TComptonTelescopeData*) libp->para[0].ref;
   const TComptonTelescopeData& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TComptonTelescopeData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTComptonTelescopeDataDict {
 public:
  G__Sizep2memfuncTComptonTelescopeDataDict(): p(&G__Sizep2memfuncTComptonTelescopeDataDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTComptonTelescopeDataDict::*p)();
};

size_t G__get_sizep2memfuncTComptonTelescopeDataDict()
{
  G__Sizep2memfuncTComptonTelescopeDataDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTComptonTelescopeDataDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData))) {
     TComptonTelescopeData *G__Lderived;
     G__Lderived=(TComptonTelescopeData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData),G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTComptonTelescopeDataDict() {

   /* Setting up typedef entry */
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TComptonTelescopeData */
static void G__setup_memvarTComptonTelescopeData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData));
   { TComptonTelescopeData *p; p=(TComptonTelescopeData*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_FrontE_TowerNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_FrontE_DetectorNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_FrontE_StripNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fCT_Tracker_FrontE_Energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_FrontT_TowerNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_FrontT_DetectorNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_FrontT_StripNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fCT_Tracker_FrontT_Time=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_BackE_TowerNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_BackE_DetectorNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_BackE_StripNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fCT_Tracker_BackE_Energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_BackT_TowerNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_BackT_DetectorNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Tracker_BackT_StripNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fCT_Tracker_BackT_Time=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Calorimeter_E_TowerNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Calorimeter_E_DetectorNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Calorimeter_E_ChannelNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fCT_Calorimeter_E_Energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Calorimeter_T_TowerNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Calorimeter_T_DetectorNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,4,"fCT_Calorimeter_T_ChannelNbr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fCT_Calorimeter_T_Time=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTComptonTelescopeDataDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTComptonTelescopeData(void) {
   /* TComptonTelescopeData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData));
   G__memfunc_setup("TComptonTelescopeData",2130,G__TComptonTelescopeDataDict_162_0_1, 105, G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__TComptonTelescopeDataDict_162_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Dump",406,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetCTTrackerFrontETowerNbr",2576,G__TComptonTelescopeDataDict_162_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - TowNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontEDetectorNbr",2873,G__TComptonTelescopeDataDict_162_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - DetNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontEStripNbr",2577,G__TComptonTelescopeDataDict_162_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - StripNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontEEnergy",2375,G__TComptonTelescopeDataDict_162_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 10 - Energy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontTTowerNbr",2591,G__TComptonTelescopeDataDict_162_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - TowNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontTDetectorNbr",2888,G__TComptonTelescopeDataDict_162_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - DetNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontTStripNbr",2592,G__TComptonTelescopeDataDict_162_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - StripNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerFrontTTime",2171,G__TComptonTelescopeDataDict_162_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 10 - Time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackETowerNbr",2424,G__TComptonTelescopeDataDict_162_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - TowNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackEDetectorNbr",2721,G__TComptonTelescopeDataDict_162_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - DetNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackEStripNbr",2425,G__TComptonTelescopeDataDict_162_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - StripNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackEEnergy",2223,G__TComptonTelescopeDataDict_162_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 10 - Energy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackTTowerNbr",2439,G__TComptonTelescopeDataDict_162_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - TowNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackTDetectorNbr",2736,G__TComptonTelescopeDataDict_162_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - DetNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackTStripNbr",2440,G__TComptonTelescopeDataDict_162_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - StripNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTTrackerBackTTime",2019,G__TComptonTelescopeDataDict_162_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 10 - Time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterETowerNbr",2482,G__TComptonTelescopeDataDict_162_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - TowNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterEDetectorNbr",2779,G__TComptonTelescopeDataDict_162_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - DetNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterEChannelNbr",2650,G__TComptonTelescopeDataDict_162_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - ChannelNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterEEnergy",2281,G__TComptonTelescopeDataDict_162_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 10 - Energy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterTTowerNbr",2497,G__TComptonTelescopeDataDict_162_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - TowNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterTDetectorNbr",2794,G__TComptonTelescopeDataDict_162_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - DetNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterTChannelNbr",2665,G__TComptonTelescopeDataDict_162_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 10 - ChannelNbr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCTCalorimeterTTime",2077,G__TComptonTelescopeDataDict_162_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 10 - Time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontEMult",2163,G__TComptonTelescopeDataDict_162_0_29, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontETowerNbr",2564,G__TComptonTelescopeDataDict_162_0_30, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontEDetectorNbr",2861,G__TComptonTelescopeDataDict_162_0_31, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontEStripNbr",2565,G__TComptonTelescopeDataDict_162_0_32, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontEEnergy",2363,G__TComptonTelescopeDataDict_162_0_33, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontTMult",2178,G__TComptonTelescopeDataDict_162_0_34, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontTTowerNbr",2579,G__TComptonTelescopeDataDict_162_0_35, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontTDetectorNbr",2876,G__TComptonTelescopeDataDict_162_0_36, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontTStripNbr",2580,G__TComptonTelescopeDataDict_162_0_37, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerFrontTTime",2159,G__TComptonTelescopeDataDict_162_0_38, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackEMult",2011,G__TComptonTelescopeDataDict_162_0_39, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackETowerNbr",2412,G__TComptonTelescopeDataDict_162_0_40, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackEDetectorNbr",2709,G__TComptonTelescopeDataDict_162_0_41, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackEStripNbr",2413,G__TComptonTelescopeDataDict_162_0_42, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackEEnergy",2211,G__TComptonTelescopeDataDict_162_0_43, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackTMult",2026,G__TComptonTelescopeDataDict_162_0_44, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTrackerTBackTTowerNbr",2427,G__TComptonTelescopeDataDict_162_0_45, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackTDetectorNbr",2724,G__TComptonTelescopeDataDict_162_0_46, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackTStripNbr",2428,G__TComptonTelescopeDataDict_162_0_47, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTTrackerBackTTime",2007,G__TComptonTelescopeDataDict_162_0_48, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterEMult",2069,G__TComptonTelescopeDataDict_162_0_49, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterETowerNbr",2470,G__TComptonTelescopeDataDict_162_0_50, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterEDetectorNbr",2767,G__TComptonTelescopeDataDict_162_0_51, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterEChannelNbr",2638,G__TComptonTelescopeDataDict_162_0_52, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterEEnergy",2269,G__TComptonTelescopeDataDict_162_0_53, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterTMult",2084,G__TComptonTelescopeDataDict_162_0_54, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterTTowerNbr",2485,G__TComptonTelescopeDataDict_162_0_55, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterTDetectorNbr",2782,G__TComptonTelescopeDataDict_162_0_56, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterTChannelNbr",2653,G__TComptonTelescopeDataDict_162_0_57, 114, -1, G__defined_typename("UShort_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCTCalorimeterTTime",2065,G__TComptonTelescopeDataDict_162_0_58, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 10 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TComptonTelescopeDataDict_162_0_59, 85, G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TComptonTelescopeData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TComptonTelescopeDataDict_162_0_60, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TComptonTelescopeData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TComptonTelescopeDataDict_162_0_61, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TComptonTelescopeData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TComptonTelescopeDataDict_162_0_62, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TComptonTelescopeData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TComptonTelescopeDataDict_162_0_66, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TComptonTelescopeDataDict_162_0_67, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TComptonTelescopeData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TComptonTelescopeDataDict_162_0_68, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TComptonTelescopeData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TComptonTelescopeDataDict_162_0_69, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TComptonTelescopeData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TComptonTelescopeDataDict_162_0_70, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TComptonTelescopeData::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TComptonTelescopeData", 2130, G__TComptonTelescopeDataDict_162_0_71, (int) ('i'), 
G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData), -1, 0, 1, 1, 1, 0, "u 'TComptonTelescopeData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TComptonTelescopeData", 2256, G__TComptonTelescopeDataDict_162_0_72, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TComptonTelescopeDataDict_162_0_73, (int) ('u'), G__get_linked_tagnum(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData), -1, 1, 1, 1, 1, 0, "u 'TComptonTelescopeData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTComptonTelescopeDataDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTComptonTelescopeDataDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTComptonTelescopeDataDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TComptonTelescopeDataDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TComptonTelescopeDataDictLN_TComptonTelescopeData = { "TComptonTelescopeData" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTComptonTelescopeDataDict() {
  G__TComptonTelescopeDataDictLN_TClass.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_TBuffer.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_TMemberInspector.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_TObject.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TComptonTelescopeDataDictLN_TComptonTelescopeData.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTComptonTelescopeDataDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TComptonTelescopeDataDictLN_TComptonTelescopeData),sizeof(TComptonTelescopeData),-1,29952,"ComptonTelescopeData structure",G__setup_memvarTComptonTelescopeData,G__setup_memfuncTComptonTelescopeData);
}
extern "C" void G__cpp_setupTComptonTelescopeDataDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTComptonTelescopeDataDict()");
  G__set_cpp_environmentTComptonTelescopeDataDict();
  G__cpp_setup_tagtableTComptonTelescopeDataDict();

  G__cpp_setup_inheritanceTComptonTelescopeDataDict();

  G__cpp_setup_typetableTComptonTelescopeDataDict();

  G__cpp_setup_memvarTComptonTelescopeDataDict();

  G__cpp_setup_memfuncTComptonTelescopeDataDict();
  G__cpp_setup_globalTComptonTelescopeDataDict();
  G__cpp_setup_funcTComptonTelescopeDataDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTComptonTelescopeDataDict();
  return;
}
class G__cpp_setup_initTComptonTelescopeDataDict {
  public:
    G__cpp_setup_initTComptonTelescopeDataDict() { G__add_setup_func("TComptonTelescopeDataDict",(G__incsetup)(&G__cpp_setupTComptonTelescopeDataDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTComptonTelescopeDataDict() { G__remove_setup_func("TComptonTelescopeDataDict"); }
};
G__cpp_setup_initTComptonTelescopeDataDict G__cpp_setup_initializerTComptonTelescopeDataDict;

