/********************************************************************
* TTigressDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTigressDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTigressDataDict();
extern void G__cpp_setup_inheritanceTTigressDataDict();
extern void G__cpp_setup_typetableTTigressDataDict();
extern void G__cpp_setup_memvarTTigressDataDict();
extern void G__cpp_setup_globalTTigressDataDict();
extern void G__cpp_setup_memfuncTTigressDataDict();
extern void G__cpp_setup_funcTTigressDataDict();
extern void G__set_cpp_environmentTTigressDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTigressData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTigressDataDictLN_TClass;
extern G__linked_taginfo G__TTigressDataDictLN_TBuffer;
extern G__linked_taginfo G__TTigressDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TTigressDataDictLN_TObject;
extern G__linked_taginfo G__TTigressDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TTigressDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TTigressDataDictLN_string;
extern G__linked_taginfo G__TTigressDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTigressDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTigressDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTigressDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTigressDataDictLN_TTigEventFragment;
extern G__linked_taginfo G__TTigressDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTigressDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDataDictLN_vectorlETH1FcOallocatorlETH1FgRsPgR;
extern G__linked_taginfo G__TTigressDataDictLN_reverse_iteratorlEvectorlETH1FcOallocatorlETH1FgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDataDictLN_TTigressData;
extern G__linked_taginfo G__TTigressDataDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
