#ifndef Analysis_h 
#define Analysis_h
/*****************************************************************************
 * Copyright (C) 2009-2014    this file is part of the NPTool Project        *
 *                                                                           *
 * For the licensing terms see $NPTOOL/Licence/NPTool_Licence                *
 * For the list of contributors see $NPTOOL/Licence/Contributors             *
 *****************************************************************************/

/*****************************************************************************
 * Original Author: Adrien MATTA  contact address: a.matta@surrey.ac.uk      *
 *                                                                           *
 * Creation Date  : march 2025                                               *
 * Last update    :                                                          *
 *---------------------------------------------------------------------------*
 * Decription:                                                               *
 * Class describing the property of an Analysis object                       *
 *                                                                           *
 *---------------------------------------------------------------------------*
 * Comment:                                                                  *
 *                                                                           *
 *                                                                           *
 *****************************************************************************/
#include"NPVAnalysis.h"
#include"NPEnergyLoss.h"
#include"NPReaction.h"
#include"RootOutput.h"
#include"RootInput.h"
#include "THiraPhysics.h"
#include "TInitialConditions.h"
#include "TInteractionCoordinates.h"
#include <TRandom3.h>
#include <TVector3.h>
#include <TMath.h>

class Analysis: public NPL::VAnalysis{
  public:
    Analysis();
    ~Analysis();

  public: 
    void Init();
    void TreatEvent();
    void End();

  void InitOutputBranch();
  void InitInputBranch();
  void ReInitValue();
  static NPL::VAnalysis* Construct();
 
  private:
  double ExcitationEnergy;
  double ELab;
  double E_ThinSi;
  double E_ThickSi;
  double E_CsI;
  double PhiLab;
  double ThetaLab;
  double ThetaLab_simu;
  double ThetaCM;
  double X,Y,Z;
  double TelescopeNumber;
  double EnergyThreshold;

  NPL::Reaction* myReaction;
  TInitialConditions* InitialConditions ;
  TInteractionCoordinates* InteractionCoordinates;

  // Energy loss table: the G4Table are generated by the simulation
  EnergyLoss LightCD2;
  EnergyLoss LightAl;
  EnergyLoss LightSi;
  EnergyLoss BeamCD2;
  
  double TargetThickness ;
  double OriginalBeamEnergy ;
  TRandom3 Rand ;
  // Hira object
  THiraPhysics* Hira;
};
#endif
